"""
Email Execution Agent — Gmail Integration
=========================================
Converts a generated outreach email into a one-click Gmail compose URL.
Zero API, zero OAuth, zero cost. Uses the standard Gmail compose deep link.

When the user clicks "Draft in Gmail":
  → Opens Gmail in a new tab with To, Subject, and Body pre-filled.
  → Salesperson reviews, edits, and sends.

Also generates a standard mailto: link as a fallback for non-Gmail users.
"""

import urllib.parse


def build_gmail_compose_url(
    subject: str,
    body: str,
    to: str = "",
    cc: str = "",
) -> str:
    """
    Build a Gmail web compose URL with pre-filled fields.

    Opens: https://mail.google.com/mail/?view=cm&su=...&body=...&to=...

    Args:
        subject:  The email subject line (generated by LLM).
        body:     The full email body (generated by LLM).
        to:       Recipient email address. Empty string is fine —
                  Gmail opens the compose window and the user types it.
        cc:       Optional CC address.

    Returns:
        A URL string that, when opened, launches Gmail compose with all fields
        pre-populated. Works with any Gmail account — no API key needed.
    """
    params: dict[str, str] = {
        "view": "cm",
    }

    if to:
        params["to"] = to
    if cc:
        params["cc"] = cc
    if subject:
        params["su"] = subject
    if body:
        params["body"] = body

    # Gmail uses standard URL encoding. urllib.parse.urlencode handles
    # special chars (\n, quotes, emojis, etc.) correctly.
    query_string = urllib.parse.urlencode(params, quote_via=urllib.parse.quote)
    return f"https://mail.google.com/mail/?{query_string}"


def build_mailto_link(
    subject: str,
    body: str,
    to: str = "",
) -> str:
    """
    Build a standard mailto: link for non-Gmail users.

    Opens the OS default email client (Outlook, Apple Mail, Thunderbird, etc.)
    with the subject and body pre-filled.

    Args:
        subject: Email subject.
        body:    Email body.
        to:      Recipient address (optional).

    Returns:
        A mailto: URI string.
    """
    headers: dict[str, str] = {}
    if subject:
        headers["subject"] = subject
    if body:
        headers["body"] = body

    encoded_headers = urllib.parse.urlencode(headers, quote_via=urllib.parse.quote)
    safe_to = urllib.parse.quote(to) if to else ""

    if encoded_headers:
        return f"mailto:{safe_to}?{encoded_headers}"
    return f"mailto:{safe_to}"


def extract_best_email_guess(enriched_data: dict) -> str:
    """
    Get the most likely email address from enriched lead data.
    Used as the 'to' field in the Gmail compose URL.

    Returns empty string if no email found (user fills it manually in Gmail).
    """
    if not enriched_data:
        return ""

    decision_makers = enriched_data.get("decision_makers", [])
    for contact in decision_makers:
        guesses = contact.get("email_guesses", [])
        if guesses:
            return guesses[0]  # Best guess for the most senior contact

    return ""
