"""
Pydantic v2 models for request/response validation and LLM output parsing.
"""
from __future__ import annotations

from pydantic import BaseModel, Field, field_validator
from typing import Optional


# ---------------------
# Input Models
# ---------------------

class ParsedLead(BaseModel):
    """Represents a parsed lead input line."""
    raw_input: str
    input_type: str = Field(description="'url' or 'name_only'")
    url: Optional[str] = None
    company_name: Optional[str] = None
    location: Optional[str] = None
    service_hint: Optional[str] = None


# ---------------------
# LLM Output: Sales Brief
# ---------------------

class SalesBrief(BaseModel):
    """Core sales brief generated by the LLM."""
    company_name: str = "Unknown"
    company_overview: str = "Not found in available content"
    core_product_service: str = "Not found in available content"
    target_customer: str = "Not found in available content"
    b2b_qualified: bool = False
    b2b_reason: str = "Not found in available content"
    sales_question_1: str = "Not found in available content"
    sales_question_2: str = "Not found in available content"
    sales_question_3: str = "Not found in available content"
    research_confidence: str = Field(default="low", description="high, medium, or low")

    @field_validator(
        'company_name', 'company_overview', 'core_product_service', 'target_customer',
        'b2b_reason', 'sales_question_1', 'sales_question_2', 'sales_question_3',
        'research_confidence', mode='before'
    )
    @classmethod
    def coerce_str(cls, v):
        """Coerce any non-string to string — LLM sometimes returns lists/ints."""
        if isinstance(v, list):
            return ' '.join(str(x) for x in v if x)
        return str(v) if v is not None else ''

    @field_validator('b2b_qualified', mode='before')
    @classmethod
    def coerce_bool(cls, v):
        """Coerce string 'true'/'false' to bool."""
        if isinstance(v, str):
            return v.lower() in ('true', 'yes', '1')
        return bool(v)



# ---------------------
# LLM Output: ICP Vertical Match
# ---------------------

class ICPMatch(BaseModel):
    """ICP matching scores against Moksh verticals."""
    mokshtech_score: int = Field(default=0, ge=0, le=100)
    mokshcad_score: int = Field(default=0, ge=0, le=100)
    mokshdigital_score: int = Field(default=0, ge=0, le=100)
    mokshsigns_score: int = Field(default=0, ge=0, le=100)
    best_fit_vertical: str = "None"
    pitch_angle: str = "Not found in available content"
    recommended_services: list[str] = Field(default_factory=list)
    # Fit detection fields — default to NOT a good fit so LLM failures don't produce false positives
    is_good_fit: bool = False
    fit_verdict: str = "Not analyzed"  # "Strong fit" | "Potential fit" | "Weak fit" | "Not a good fit" | "Not analyzed"
    rejection_reason: str = "Analysis could not be completed"
    vertical_explanations: dict = Field(default_factory=dict)  # {vertical_name: explanation}

    @field_validator('best_fit_vertical', mode='before')
    @classmethod
    def coerce_vertical(cls, v):
        """Handle pipe-separated or list values — take only the first."""
        if isinstance(v, list):
            return str(v[0]) if v else 'None'
        if isinstance(v, str) and '|' in v:
            return v.split('|')[0].strip()
        return str(v) if v is not None else 'None'

    @field_validator('pitch_angle', mode='before')
    @classmethod
    def coerce_pitch(cls, v):
        if isinstance(v, list):
            return ' '.join(str(x) for x in v)
        return str(v) if v is not None else 'Not found in available content'

    @field_validator('recommended_services', mode='before')
    @classmethod
    def coerce_services(cls, v):
        if isinstance(v, str):
            return [s.strip() for s in v.split(',') if s.strip()]
        return v or []

    @field_validator('fit_verdict', mode='before')
    @classmethod
    def coerce_fit_verdict(cls, v):
        if isinstance(v, list):
            return str(v[0]) if v else 'Potential fit'
        return str(v) if v else 'Potential fit'

    @field_validator('rejection_reason', mode='before')
    @classmethod
    def coerce_rejection_reason(cls, v):
        if isinstance(v, list):
            return '. '.join(str(x) for x in v if x)
        return str(v) if v is not None else ''

    @field_validator('vertical_explanations', mode='before')
    @classmethod
    def coerce_vertical_explanations(cls, v):
        if isinstance(v, dict):
            return {str(k): str(val) for k, val in v.items()}
        return {}

    @field_validator('is_good_fit', mode='before')
    @classmethod
    def coerce_is_good_fit(cls, v):
        if isinstance(v, str):
            return v.lower() in ('true', 'yes', '1')
        return bool(v) if v is not None else True


# ---------------------
# LLM Output: Market Context
# ---------------------

class MarketContext(BaseModel):
    """Market positioning and differentiation analysis."""
    positioning: str = "Not found in available content"
    differentiation_signals: str = "Not found in available content"
    opportunity_gaps: str = "Not found in available content"
    ai_inferred: bool = False

    @field_validator('positioning', 'differentiation_signals', 'opportunity_gaps', mode='before')
    @classmethod
    def coerce_string_fields(cls, v):
        """Coerce lists to joined strings — LLM sometimes returns arrays."""
        if isinstance(v, list):
            return '. '.join(str(x) for x in v if x)
        return str(v) if v is not None else 'Not found in available content'


# ---------------------
# LLM Output: Outreach Email
# ---------------------

class OutreachEmail(BaseModel):
    """Generated cold outreach email."""
    subject: str = ""
    body: str = ""


# ---------------------
# LLM Output: Objection Preparation
# ---------------------

class Objection(BaseModel):
    """Single objection with counter-response."""
    objection: str
    counter: str


class ObjectionPrep(BaseModel):
    """Objection preparation sheet."""
    objections: list[Objection] = Field(default_factory=list)


# ---------------------
# API Request/Response Models
# ---------------------

class AnalyzeRequest(BaseModel):
    """Request body for the analyze endpoint."""
    leads_text: str = Field(description="Raw text with one lead per line")


class LeadStatus(BaseModel):
    """Status of a single lead in a job."""
    lead_id: str
    company_name: Optional[str] = None
    raw_input: str
    status: str = "queued"
    error_message: Optional[str] = None


class JobStatusResponse(BaseModel):
    """Response for job status polling."""
    job_id: str
    status: str
    lead_count: int
    completed_count: int
    leads: list[LeadStatus] = Field(default_factory=list)
